GitLab_CI_Runner:
  pkg.installed:
    - pkgs: 
        - wget 
        - curl 
        - gcc 
        - libxml2-dev
        - libxslt-dev
        - libcurl4-openssl-dev
        - libreadline6-dev 
        - libc6-dev 
        - libssl-dev 
        - make 
        - build-essential
        - zlib1g-dev 
        - openssh-server 
        - git-core 
        - libyaml-dev 
        - postfix 
        - libpq-dev 
        - libicu-dev
